apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-b
  namespace: argocd
spec:
  description: Proyecto del equipo B
  sourceRepos:
    - https://github.com/rcorderoayigroup/team-b.git
  destinations:
    - namespace: team-b
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
